### PR TITLE
add ability to pull in image from docker registry

### PR DESCRIPTION
**Pull request by talevy**
I do not think this is ideal, but Docker does not really provide another way to pull new images.

here is a discussion surrounding more features around image pulls: https://github.com/docker/docker/issues/6928

### CODE REVIEW

**Comment by talevy** [comment]
@untergeek let me know what you think!

**Comment by untergeek** [comment]
EXACTLY!  I was planning on trying to do this without resorting to command-line tools, though—especially because if we're doing remote work won't it pull to the wrong location?

I was thinking of adding this via pull request to the docker api gem repo...

**Comment by talevy** [comment]
it will run this docker command against the configured `DOCKER_HOST` in the current shell environment.

**Comment by untergeek** [comment]
cool then!

**Pull request merged**
